# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

R_compact_rep <- function(n, v) {
    .Call(`_altreplicate_R_compact_rep`, n, v)
}

R_is_altrep <- function(x) {
    .Call(`_altreplicate_R_is_altrep`, x)
}

R_is_materialized <- function(x) {
    .Call(`_altreplicate_R_is_materialized`, x)
}

